### ISSUE TITLE
output issue

### ISSUE THREAD

**Issue by June-hui** [VITA-Group/DeepPS#21]
Is your model correct? Why are all the images I output error?( all my output images are one color) hope your reply~

**Comment by williamyang1991** [comment]
Did you try the sample data we provided in data/STN and data/EDT? Are the results still one color?
I cannot help you with the little information you provided.

**Comment by June-hui** [comment]
> Did you try the sample data we provided in data/STN and data/EDT? Are the results still one color? I cannot help you with the little information you provided.

thank your answer，data/STN and data/EDT 's result all are  one color. i use python3.7 ,pytorch1.2.0+cuda9.2 for windows.

**Comment by June-hui** [comment]
Could you provide the detail of packages required for installing in windows ? For example, the version of package, thank you.

**Comment by williamyang1991** [comment]
I tried my code on linux. I didn't test on Windows. 
If I find time this week, I will test on Windows and tell you the packages.

**Comment by williamyang1991** [comment]
Here is how I install all the packages 
(python 2.7 is not supported for current torch version, so I install the python 3.8 for recent pytorch version)
```
git clone https://github.com/TAMU-VITA/DeepPS.git
cd DeepPS/src
conda create --name deepPS python=3.8 
conda activate deepPS    
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
conda install matplotlib   
conda install scipy     
conda install Pillow 
conda install -c conda-forge opencv 

# these are for the installation of torchsample. 
git clone https://github.com/ncullen93/torchsample.git  
cd torchsample   
python setup.py install
cd ..
conda install pandas   
pip install nibabel
pip install tqdm
```

After downloading the pretrained models to ``./save/``, removing the original results in ``./output/``, I run the code
```
python test.py
```
I got the results:
![results](https://github.com/VITA-Group/DeepPS/assets/18130694/036030dc-1608-454d-8d21-f165b2f737b4)

**Comment by June-hui** [comment]
Thank you very much!
