### ISSUE TITLE
Training on customized data

### ISSUE THREAD

**Issue by dujiaxin** [VITA-Group/DeepPS#3]
I would like to train this model on a customized dataset like you did with purse and other stuff.
But it requires an F network, which I cannot find more information about.
How you pre-trained model F? Do you have code for that?

**Comment by williamyang1991** [comment]
It just follow the training pipeline of pix2pix.
I think I can clean up and release my pix2pix code for your reference.

**Comment by williamyang1991** [comment]
> I would like to train this model on a customized dataset like you did with purse and other stuff.
> But it requires an F network, which I cannot find more information about.
> How you pre-trained model F? Do you have code for that?

I have added a new file trainPix2pix.py in src
