### ISSUE TITLE
how to put photo and sketch as input?

### ISSUE THREAD

**Issue by molo32** [VITA-Group/DeepPS#4]
the example just uses sketch as input.

**Comment by williamyang1991** [comment]
This code gives the example
You can find 4.png in DeepPS/data/EDT/ where both sketch, photo and mask are given

> python test.py --model_task EDT --input_name ../data/EDT/4.png \
> --load_F_name ../save/ECCV-EDT-celebaHQ-F256.ckpt --model_name ECCV-EDT-celebaHQ
